<a href="https://colab.research.google.com/github/zhangyuwen193-cell/114-2-Programing-Language/blob/main/%E4%BD%9C%E6%A5%AD%E4%B8%80part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1GCVRpR7jj_Rr6NQJBlV-mOTbjiQxS9rlPe9lYqfXZhs/edit?gid=0#gid=0

In [63]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [113]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1GCVRpR7jj_Rr6NQJBlV-mOTbjiQxS9rlPe9lYqfXZhs/edit?gid=0#gid=0')

In [159]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

           日期    時間  分類  品項  金額  付款人  地點 支付方式   備註
0  2024-04-03  7:40  交通  捷運  40  張語宸  公館  悠遊卡  回宿舍
1  2024-04-03  7:40  交通  捷運  40  張語宸  公館  悠遊卡  回宿舍

In [139]:
import datetime

In [140]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

type_str = input("請輸入分類: ")

item = input("請輸入品項: ")

amount = float(input("請輸入金額: "))

people = input("請輸入付款人: ")

place_str = input("請輸入地點: ")

way = input("請輸入付款方式: ")

other = input("請輸入備註: ")

請輸入日期 (格式：YYYY-MM-DD): 2024-04-03
請輸入時間 (格式：HH:MM): 07:40
請輸入分類: 交通
請輸入品項: 捷運
請輸入金額: 40
請輸入付款人: 張語宸
請輸入地點: 公館
請輸入付款方式: 悠遊卡
請輸入備註: 回宿舍

In [141]:
date_str

'2024-04-03'

In [142]:
time_str

'07:40'

In [143]:
type_str

'交通'

In [144]:
item

'捷運'

In [145]:
amount

40.0

In [146]:
people

'張語宸'

In [147]:
place_str

'公館'

In [148]:
way

'悠遊卡'

In [149]:
other

'回宿舍'

In [152]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': type_str,
    '品項': item,
    '金額': amount,
    '付款人': people,
    '地點': place_str,
    '付款方式': way,
    '備註': other,


}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [160]:
df

           日期    時間  分類  品項  金額  付款人  地點 支付方式   備註
0  2024-04-03  7:40  交通  捷運  40  張語宸  公館  悠遊卡  回宿舍
1  2024-04-03  7:40  交通  捷運  40  張語宸  公館  悠遊卡  回宿舍

In [158]:
worksheet = gsheets.worksheet('工作表1')

new_row = [date_str, time_str, type_str, item, amount, people, place_str, way, other]  # 順序要跟表頭一致
worksheet.append_row(new_row, value_input_option='USER_ENTERED')

print("✅ 已新增 1 筆資料")

✅ 已新增 1 筆資料